export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS'
export const USER_CREATE_FAIL = 'USER_CREATE_FAIL'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'



export const SUCCESS_MESSAGE_CLEAR = 'SUCCESS_MESSAGE_CLEAR'
export const ERROR_CLEAR = 'ERROR_CLEAR'


export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'