export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_GET_SUCCESS = 'ORDER_GET_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'
export const ORDER_GET_FAIL = 'ORDER_GET_FAIL'


export const ORDER_SUCCESS_MESSAGE_CLEAR = 'ORDER_SUCCESS_MESSAGE_CLEAR'
export const ORDER_ERROR_CLEAR = 'ORDER_ERROR_CLEAR'

